POST http://127.0.0.1:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFscGhhQGdvb2QuY29tIiwiZXhwIjoxNzI2MzUxODQxLCJ1c2VySWQiOjF9.IYl7hl7FTuV5IhNnDc8Ihk1_DSDApswT1F4Xe-ZFAnQ


{
	"title": "GoRocks",
	"description": "IA WILL STEAL OUR JOBS FOR FUCK SAKE",
	"location": "EVERYWHERE, WE ARE DOOOMED",
	"datetime": "2035-01-01T15:30:00Z"
}