DELETE http://127.0.0.1:8080/events/20
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFscGhhQGdvb2QuY29tIiwiZXhwIjoxNzI2MzUzMDY1LCJ1c2VySWQiOjF9.mUzhrY2nozXvmlrlmxRaZOxa_9dp7XeqO6bWw2rUtQ8