DELETE http://127.0.0.1:8080/events/30
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFscGhhQGdvb2QuY29tIiwiZXhwIjoxNzI2Mzk5NTYxLCJ1c2VySWQiOjF9.tdmCEXDnpFlvTv2CbSzBNTTk7lcS2bFWG0SHELRN6bc