PUT http://127.0.0.1:8080/events/30
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFscGhhQGdvb2QuY29tIiwiZXhwIjoxNzI2NDAxOTIxLCJ1c2VySWQiOjF9.HG9YopbwlzVu0rR81WdpMwnhVT3G2VLUFZaMu1Gl864

{
	"title": "AllIsGood",
	"description": "We'll be fine!",
	"location": "Our planet Earth",
	"datetime": "2035-01-01T15:30:00Z"
}